### ISSUE TITLE
Problème sur fire cube

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [nextv-apps/android-tv-beta-test#1]
L'application se met en veille sur fire cube au bout de 3 minutes de lecture d'un film.  

Les séries ne se mettent pas à jour dans ma liste, donc on sait pas quand une série est mise à jour. 

Sinon le player est pas mal

**Comment by sbenmeddour** [comment]
Bonjour, merci pour le retour

Les problèmes sont identifiés et seront corrigés pour la version `3.1.1`

**Comment by TechComputerServiceDunkerque** [comment]
> Bonjour, merci pour le retour
> 
> Les problèmes sont identifiés et seront corrigés pour la version `3.1.1`

J'essaierai ce soir, je vous ferais un rapport de tout ce qui va et tout ce qui va pas, comme ça vous aurez quelques choses de complet pour faire des améliorations 👍

**Comment by TechComputerServiceDunkerque** [comment]
> Bonjour, merci pour le retour
> 
> Les problèmes sont identifiés et seront corrigés pour la version `3.1.1`

Pour la catégorie ma liste, serait-il possible d'installer un tri, c'est à dire: 

- Par ordre alphabétique dans la playlist.
- Par note
- Par dernière modification. (Car les séries qui sont dans mes favoris, je ne vois pas lorsqu'elles sont maj, cette option serait vraiment utile). 

Merci
